name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your .NET SDK version (8.0.6)

      - name: Build and publish
        run: |
          dotnet publish -c Release -o build

      - name: Modify base URL in index.html
        run: |
          sed -i 's|<base href="/">|<base href="/pwaDemo/">|g' build/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.SAMPLE }}
          BRANCH: gh-pages
          FOLDER: build/wwwroot
          CLEAN: true  # Optional: Ensures the target folder is cleaned before deploying

