name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - master  # Trigger on push to the main branch

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your .NET SDK version (8.0.x)

      - name: Publish .NET Core Project
        run: dotnet publish pwaDemo.csproj -c Release -o release --nologo

      - name: Change base tag in index.html
        run: sed -i 's|<base href="/">|<base href="/pwaDemo/">|g' release/wwwroot/index.html

      - name: Fix service-worker-assets.js hashes
        working-directory: release/wwwroot
        run: |
          jsFile=$(<service-worker-assets.js)
          json=$(echo "$jsFile" | sed 's/self\.assetsManifest = //g; s/;//g')
          assets=$(echo "$json" | jq '.assets[]' -c)
          for asset in $assets; do
            oldHash=$(echo "$asset" | jq -r '.hash')
            path=$(echo "$asset" | jq -r '.url')
            newHash="sha256-$(openssl dgst -sha256 -binary $path | openssl base64 -A)"
            
            if [ "$oldHash" != "$newHash" ]; then
              oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
              newHash=$(echo "$newHash" | sed 's;/;\\/;g')
              echo "Updating hash for $path from $oldHash to $newHash"
              jsFile=$(echo -n "$jsFile" | sed "s;$oldHash;$newHash;g")
            fi
          done
          echo -n "$jsFile" > service-worker-assets.js

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.SAMPLE}}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
